name: CI/CD pipeline test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
  AWS_HOST: ${{ secrets.AWS_HOST }}
  AWS_SSH_KEY: ${{ secrets.AWS_SSH_KEY }}
  AWS_USER: ${{ secrets.AWS_USER }}
  GPT_API_KEY: ${{ secrets.GPT_API_KEY }}


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: |
          docker login -u ${{ env.DOCKER_HUB_USERNAME }} -p ${{ env.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ env.DOCKER_REPO }}:latest .
          docker push ${{ env.DOCKER_REPO }}:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: EC2 Docker Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.AWS_HOST }}
          username: ${{ env.AWS_USER }}
          key: ${{ env.AWS_SSH_KEY }}
          script: |
            docker login -u ${{ env.DOCKER_HUB_USERNAME }} -p ${{ env.DOCKER_HUB_ACCESS_TOKEN }}

            # 기존 컨테이너가 있다면 중지 및 제거
            if docker ps -a | grep -q "Block-Guard-AI"; then
              docker stop Block-Guard-AI || true
              docker rm Block-Guard-AI || true
            fi

            docker pull "${{ env.DOCKER_REPO }}:latest"

            docker run -d \
              --name "Block-Guard-AI" \
              -p 8000:8000 \
              -e GPT_API_KEY="${{ env.GPT_API_KEY }}" \
              ${{ env.DOCKER_REPO }}:latest